
import { Sora } from "next/font/google";
import "./globals.css";
import Nav from '../components/nav/Nav'
import Header from '../components/header/Header'
import TopLeftImg from '../components/topLeftImg/TopLeftImg'
import AnimationWrapper from "@/components/transition/Transition";

// framer motion

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "DABSMANUEL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <main className="page bg-site text-white bg-cover bg-no-repeat relative">
          <TopLeftImg/>
          <Nav />
          <Header />
          <AnimationWrapper>{children}</AnimationWrapper>   
            

        </main>
      </body>
    </html>
  );
}
